### ISSUE TITLE
About the purchase logic

### ISSUE THREAD

**Issue by Airrcat** [Escapingbug/dotaxctf#22]
I didn't see in the relevant documentation and source code how to purchase equipment between rounds, or at the beginning of the game. I'm confused now how to purchase

**Comment by kdxcxs** [comment]
Here is a demo script with most of available api and equipment purchasing is included, see [default action](https://github.com/Escapingbug/dotaxctf/blob/master/bot/default_action.lua#L39).

**Comment by Airrcat** [comment]
> Here is a demo script with most of available api and equipment purchasing is included, see [default action](https://github.com/Escapingbug/dotaxctf/blob/master/bot/default_action.lua#L39).


Thanks, I did not change the server path when I started it for the first time, now it is ok
